-- Atmosense managed data layer
-- Run this migration in the Supabase SQL Editor.
-- Keep the anon key public only; never expose SUPABASE_SERVICE_ROLE_KEY.
create extension if not exists pgcrypto;

create table if not exists public.devices (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    name text not null check (char_length(name) between 1 and 100),
    location text not null default 'Unassigned' check (char_length(location) <= 120),
    device_type text not null default 'ESP32 + DHT11' check (char_length(device_type) <= 100),
    enabled boolean not null default true,
    last_seen timestamptz,
    constraint devices_id_owner_key unique (id, owner_id)
  );

create table if not exists public.telemetry (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    device_id text not null,
    temperature_c numeric not null check (temperature_c between -80 and 100),
    constraint telemetry_device_owner_fk foreign key (device_id, owner_id)
      references public.devices(id, owner_id) on delete cascade,
    humidity_percent numeric not null check (humidity_percent between 0 and 100),
    rssi_dbm numeric,
    recorded_at timestamptz not null default now()
  );

create table if not exists public.alert_settings (
    owner_id uuid primary key references auth.users(id) on delete cascade,
    enabled boolean not null default true,
    temperature_low numeric not null default 18 check (temperature_low < temperature_high),
    temperature_high numeric not null default 32,
    humidity_low numeric not null default 30 check (humidity_low < humidity_high),
    humidity_high numeric not null default 70
  );

-- Add ownership constraints to databases created from an earlier revision.
do $$
begin
  if exists (
    select 1 from public.telemetry t
    join public.devices d on d.id=t.device_id
    where t.owner_id is distinct from d.owner_id
  ) then
    raise exception 'Cannot add telemetry owner constraint: existing owner mismatches found';
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname='devices_id_owner_key' and conrelid='public.devices'::regclass
  ) then
    alter table public.devices add constraint devices_id_owner_key unique (id, owner_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname='telemetry_device_owner_fk' and conrelid='public.telemetry'::regclass
  ) then
    alter table public.telemetry add constraint telemetry_device_owner_fk
      foreign key (device_id, owner_id) references public.devices(id, owner_id) on delete cascade;
  end if;
end $$;

alter table public.devices enable row level security;
alter table public.telemetry enable row level security;
alter table public.alert_settings enable row level security;

drop policy if exists "users manage their devices" on public.devices;
drop policy if exists "users read their telemetry" on public.telemetry;
drop policy if exists "trusted ingestion writes telemetry" on public.telemetry;
drop policy if exists "service role ingests telemetry" on public.telemetry;
drop policy if exists "users manage their alert settings" on public.alert_settings;

create policy "users manage their devices" on public.devices for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "users read their telemetry" on public.telemetry for select to authenticated using (auth.uid()=owner_id);
-- The server's private ingestion client inserts owner_id after looking up the registered device.
-- No anon/authenticated client can insert telemetry directly.
create policy "service role ingests telemetry" on public.telemetry for insert to service_role with check (true);
create policy "users manage their alert settings" on public.alert_settings for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);

create index if not exists telemetry_owner_time_idx on public.telemetry(owner_id, recorded_at desc);
create index if not exists telemetry_device_time_idx on public.telemetry(device_id, recorded_at desc);

-- Optional hardening for deployments that use the Supabase database REST API.
revoke all on public.devices from anon;
revoke all on public.telemetry from anon;
revoke all on public.alert_settings from anon;
