-- Atmosense managed data layer
-- Run in Supabase SQL Editor. Keep the anon key public only; never expose service-role keys.
create extension if not exists pgcrypto;

create table if not exists public.devices (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    location text default 'Unassigned',
    device_type text default 'ESP32 + DHT11',
    enabled boolean not null default true,
    last_seen timestamptz
  );

create table if not exists public.telemetry (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    device_id text not null references public.devices(id) on delete cascade,
    temperature_c numeric not null,
    humidity_percent numeric not null,
    rssi_dbm numeric,
    recorded_at timestamptz not null default now()
  );

create table if not exists public.alert_settings (
    owner_id uuid primary key references auth.users(id) on delete cascade,
    enabled boolean not null default true,
    temperature_low numeric not null default 18,
    temperature_high numeric not null default 32,
    humidity_low numeric not null default 30,
    humidity_high numeric not null default 70
  );

alter table public.devices enable row level security;
alter table public.telemetry enable row level security;
alter table public.alert_settings enable row level security;

create policy "users manage their devices" on public.devices for all using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "users read their telemetry" on public.telemetry for select using (auth.uid()=owner_id);
create policy "trusted ingestion writes telemetry" on public.telemetry for insert with check (auth.uid()=owner_id);
create policy "users manage their alert settings" on public.alert_settings for all using (auth.uid()=owner_id) with check (auth.uid()=owner_id);

create index if not exists telemetry_owner_time_idx on public.telemetry(owner_id, recorded_at desc);
create index if not exists telemetry_device_time_idx on public.telemetry(device_id, recorded_at desc);
