require('dotenv').config();const fs=require('fs');const path=require('path');const crypto=require('crypto');const express=require('express');const mqtt=require('mqtt');
const PORT=Number(process.env.PORT||3000),ENDPOINT=process.env.AWS_IOT_ENDPOINT,TOPIC=process.env.MQTT_TOPIC||'environment/dht11',CERT_DIR=process.env.CERT_DIR||'../secrets',MOCK=String(process.env.MOCK_DATA||'false').toLowerCase()==='true';
const app=express(),recent=[],clients=new Set(),sessions=new Map();const DATA_DIR=path.join(__dirname,'data'),USERS_FILE=path.join(DATA_DIR,'users.json');fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(USERS_FILE))fs.writeFileSync(USERS_FILE,'[]');
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const readUsers=()=>JSON.parse(fs.readFileSync(USERS_FILE,'utf8'));const saveUsers=u=>fs.writeFileSync(USERS_FILE,JSON.stringify(u,null,2));const cleanUser=u=>({id:u.id,name:u.name,email:u.email});
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`}function validPassword(password,stored){const [salt,key]=stored.split(':');return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(password,salt,64))}function sessionUser(req){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('atmosense_session='))?.split('=')[1];return token?sessions.get(token):null}function setSession(res,user){const token=crypto.randomBytes(32).toString('hex');sessions.set(token,user);res.setHeader('Set-Cookie',`atmosense_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`)}
app.post('/api/auth/signup',(req,res)=>{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(name.length<2||!email.includes('@')||password.length<8)return res.status(400).json({error:'Enter a name, valid email, and password of at least 8 characters.'});const users=readUsers();if(users.some(u=>u.email===email))return res.status(409).json({error:'An account with this email already exists.'});const user={id:crypto.randomUUID(),name,email,passwordHash:hashPassword(password),createdAt:new Date().toISOString()};users.push(user);saveUsers(users);const safe=cleanUser(user);setSession(res,safe);res.status(201).json(safe)});
app.post('/api/auth/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const user=readUsers().find(u=>u.email===email);if(!user||!validPassword(password,user.passwordHash))return res.status(401).json({error:'Email or password is incorrect.'});const safe=cleanUser(user);setSession(res,safe);res.json(safe)});
app.get('/api/auth/me',(req,res)=>{const user=sessionUser(req);if(!user)return res.status(401).json({error:'Not signed in'});res.json(user)});app.post('/api/auth/logout',(req,res)=>{const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('atmosense_session='))?.split('=')[1];if(token)sessions.delete(token);res.setHeader('Set-Cookie','atmosense_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/latest',(_req,res)=>res.json({latest:recent.at(-1)||null,recent}));app.get('/events',(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive'});res.flushHeaders();clients.add(res);const last=recent.at(-1);if(last)res.write(`data: ${JSON.stringify(last)}\n\n`);req.on('close',()=>clients.delete(res))});
function publishReading(reading){const item={...reading,received_at:new Date().toISOString()};recent.push(item);while(recent.length>60)recent.shift();const message=`data: ${JSON.stringify(item)}\n\n`;for(const client of clients)client.write(message)}
if(MOCK||!ENDPOINT){console.log('Running in SAMPLE_DATA demo mode. Set AWS_IOT_ENDPOINT and MOCK_DATA=false for AWS IoT Core.');const sampleFile=path.join(__dirname,'data','sample-readings.json');const sample=fs.existsSync(sampleFile)?JSON.parse(fs.readFileSync(sampleFile,'utf8')):[];let sampleIndex=0;const emitSample=()=>{const reading=sample.length?sample[sampleIndex++%sample.length]:{device_id:'demo-esp32-dht11',temperature_c:26.8,humidity_percent:55.2,rssi_dbm:-55};publishReading(reading)};emitSample();setInterval(emitSample,3000)}else{const read=name=>fs.readFileSync(path.resolve(__dirname,CERT_DIR,name));const client=mqtt.connect(`mqtts://${ENDPOINT}:8883`,{clientId:`dashboard-${Date.now()}`,ca:read('AmazonRootCA1.pem'),cert:read('dashboard-certificate.pem.crt'),key:read('dashboard-private.pem.key'),clean:true,reconnectPeriod:3000});client.on('connect',()=>{console.log(`Connected to AWS IoT Core; subscribing to ${TOPIC}`);client.subscribe(TOPIC)});client.on('message',(_topic,payload)=>{try{publishReading(JSON.parse(payload.toString()))}catch(e){console.error('Invalid telemetry:',e.message)}});client.on('error',err=>console.error('MQTT error:',err.message))}
app.listen(PORT,()=>console.log(`Atmosense available at http://localhost:${PORT}`));
